### ISSUE TITLE
Replaces only first space in test file name

### ISSUE THREAD

**Issue by dotokoto** [yandex/storytests-webpack-plugin#5]
Actual: Story with name `With remove control` creates a file named `With-remove control.hermione.js`
Expected: File name will be `With-remove-control.hermione.js`

**Comment by baushonok** [comment]
Fixed in 1.0.6 (`storytests-webpack-plugin@1.0.6`)

**Comment by baushonok** [comment]
Example is [here](https://github.com/baushonok/tested-storybook/pull/6)
